version: "3"

services:
  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postmangovsg_dev
    ports:
      - "5432:5432"
    volumes:
      - pg-data12:/var/lib/postgresql/data
  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
  maildev:
    image: maildev/maildev
    environment:
      - MAILDEV_OUTGOING_USER=admin
      - MAILDEV_OUTGOING_PASS=123 
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "1025:1025"  
volumes:
  pg-data12: